#!/usr/bin/env bash

# path to notifier
notifier=changenotifierpath
# path to cleanit
cleanit=changecleanitpath
echo ${cleanit}
# clean Download
# store the output to a variable
download_notice=$($cleanit)
# echo ${download_notice}
# clean Trash
trash_notice=$($cleanit -f trash -d changedays)

$notifier -message "Downloads cleanup: ${download_notice}"
$notifier -message "Trash cleanup: ${trash_notice}"
