#!/bin/bash

# path to notifier
notifier=changenotifierpath
# path to cleanit
cleanit=changecleanitpath
# clean-up Download
# store the output to a variable
download_notice=$($cleanit)
# clean-up Trash
trash_notice=$($cleanit -f trash -d changedays)

$notifier -message "Downloads cleanup: ${download_notice}"
$notifier -message "Trash cleanup: ${trash_notice}"
